char_dict = {
    "Goku (Mid)": "img/chars/goku_mid.png",
    "Shadow the Hedgehog": "img/chars/shadow_the_hedgehog.png",
    "Dorothy (Nikke)": "",
    "Hustler-1": "",
    "Nemo (AC)": "",
    "Gohan Calvo": "",
    "Rena Hirose (AC)": "",
    "Asterix": "",
    "Obelix": "",
    "Leos Klein": "",
    "Stinger": "",
    "Scarface (AC)": "",
    "Malcolm (UT)": "",
    "Abyssal Dision": "",
    "Mobius-1": "",
    "Blaze (AC)": "",
    "Blaze the Cat": "",
}

org_dict = {
    "Raven's Nest": "img/orgs/raven_nest.png",
    "Emeraude": "",
    "Chrome": "",
    "Murakumo Millenium": "",
    "PROGTECH": "",
    "Neucom": "",
    "Liandri": "",
    "Twitch Staff": "",
    "Global Cortex": "",
    "Chemical-Dyne": "",
    "Struggle": "",
    "UPEO": "",
    "General Resource": "",
    "Zio Matrix": "",
    "Crest": "",
    "Mirage": "",
    "Kisaragi": "",
    "ISAF": "",
}

req_dict = {
    "Vargskelethor": "",
    "Miles 'Tails' Prower": "img/reqs/tails.png",
    "Sugar (Nikke)": "",
    "Neromatsu": "",
    "Billy Kid (ZZZ)": "",
    "Big the Cat": "",
    "Froggy": "",
    "Doro": "",
    }

extra_dict = {
    "MT": "img/extra/mt.png",
    "Stinger": "",
    "Nine Ball": "",
    "Rapture (Nikke)": "",
    "Gun Hunter (Sonic)": "",
    "Frieza Soldier": "",
    "Saibaman": "",
    "R-101": "",
    "Su-37": "",
    "Disorder Unit": "",
    "Goomba": "",
    "Chuckya": "",
    "Arkbird (AC)": "",
}

loc_dict = {
    "Montevideo": "",
    "Kame House": "img/locs/kame_house.png",
    "Space Colony ARK": "",
    "The Ark (Nikke)": "",
    "Zam City": "",
    "Isaac City": "",
    "Eusian Ocean": "",
    "Megafloat (AC)": "",
    "Vihul Spaceport": "",
    "Zio Matrix's HQ": "",
    "Murakumo Dome": "",
    "PROGTECH Factory": "",
    "Amber Crown": "",
    "Trene City": "",
    "Arena": "",
    "Ruglen Lab": "",
    "Stonehenge (AC)": "",
    "Megalith (AC)": "",
    "Facing Worlds": "",
}
